

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdatabase?serverTimezone=UTC
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400    # 초

#  batch:
#    jdbc:
#      initialize-schema: always

logging.level:
  org.hibernate.SQL: debug
  "[org.hibernate.type]": trace #스프링 부트 2.x, hibernate5


